services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - nodered-frontend
      - nodered-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  mongo:
    image: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

  nodered-frontend:
    build: ./customNodeRed
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
    depends_on:
      - mongo
    ports:
      - "1880:1880"

  nodered-api:
    build: ./customNodeRed
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
    depends_on:
      - mongo
    deploy:
      replicas: 3
    ports:
      - "1880"
